rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php ./bin/rr-worker start"
  relay: pipes
  env:
    TERM_PROGRAM: Hyper

http:
  address: 0.0.0.0:8000
  middleware: [ "gzip", "websockets" ]
  pool:
    max_jobs: 64 # feel free to change this
    supervisor:
      exec_ttl: 60s
  static:
    dir: "public"
    forbid: [ ".php" ]

websockets:
  broker: default
  path: "/ws"

broadcast:
  default:
    driver: memory
    config: {}

kv:
  session:
    driver: memory
    config: {}

jobs:
  consume: [ "default", "events" ]
  pipelines:
    default:
      driver: memory
    events:
      driver: memory

logs:
  level: info
  mode: raw
  line_ending: "\r"

service:
  monolog:
    command: "php artisan monolog:start --host=0.0.0.0 --port=9913"
    process_num: 1
  var-dumper:
    command: "php artisan var-dumper:start --host=0.0.0.0 --port=9912"
    process_num: 1
  smtp:
    command: "php artisan smtp:start --host=0.0.0.0 --port=1025"
    process_num: 1
