version: "2"
services:
    php:
        build: "./docker/server"
        restart: unless-stopped
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_DATABASE: homestead
            DB_USERNAME: homestead
            DB_PASSWORD: secret
        ports:
        - 8000:8000
        volumes:
            - ./:/app
        depends_on:
            - db

    db:
        image: postgres
        environment:
            POSTGRES_USER: homestead
            POSTGRES_DB: homestead
            POSTGRES_PASSWORD: secret

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8011:8080
        depends_on:
            - db
