version: "2"
services:
    php:
        build: "./docker/server"
        restart: unless-stopped
        ports:
        - 8000:8000
        - 23518:23518
        volumes:
            - ./:/app
volumes:
    web-root:
        driver: local
