version: "2"
services:
    buggregator:
        image: butschster/buggregator:latest

    php:
        build: "./docker/server"
        #restart: unless-stopped
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_DATABASE: homestead
            DB_USERNAME: homestead
            DB_PASSWORD: secret
        ports:
            - 8000:8000
            - 1025:1025
            - 9912:9912
            - 9913:9913
        volumes:
            - ./:/app
        depends_on:
            - db
            - buggregator

    db:
        image: postgres
        environment:
            POSTGRES_USER: homestead
            POSTGRES_DB: homestead
            POSTGRES_PASSWORD: secret

#    rabbitmq:
#        image: rabbitmq:3-management-alpine
#        environment:
#            - RABBITMQ_DEFAULT_USER=admin
#            - RABBITMQ_DEFAULT_PASS=admin

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8011:8080
        depends_on:
            - db
